import Head from "next/head";
import Trending from "../components/Trending";
import { getTrending } from "../services/data";
import { RootTrendingType } from "../types/movieTypes";
import { GetServerSideProps } from "next";

export type InferdTrendingProps = {
  data: RootTrendingType
}

const Home = ({data}: InferdTrendingProps) => {
  return (
    <>
      <Head>
        <title>HOME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
        <Trending data={data} />
      </div>
    </>
  );
}
export default Home;

export const getServerSideProps: GetServerSideProps<{
  data: RootTrendingType;
}> = async () => {
  const res = await fetch(getTrending());

  const data: RootTrendingType = await res.json();

  return {
    props: {
      data,
    },
  };
};
