import Head from "next/head";
import SearchInput from "../components/SearchInput";
import Slider from "../components/CardImage";
import Trending from "../components/Trending";
import { getTrending } from "../services/data";

export default function Home({data}: any) {
  return (
    <>
      <Head>
        <title>HOME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <Trending data={data}/>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch(getTrending());

  const data = await res.json();

  return {
    props: {
      data: data.results,
    },
  };
}
